version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          - PORT: 3000
          - PGUSER: 'test'
          - PGPASSWORD: 'test'
          - PGDATABASE: 'test'
          - PGHOST: 'localhost'
          - PGPORT: '5432'
    
      - image: circleci/postgres:10.1
        environment:
          - POSTGRES_USER: test
          - POSTGRES_DB: test
          - POSTGRES_PASSWORD: test

    steps:
      - checkout
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      - run:
          name: Change permissions from root to user
          command: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

      - run:
          name: Clean npm cache
          command: npm cache clean --force npm config set -g production false

      - run:
          name: Set npm environment to dev
          command: npm config set -g production false

      - run:
          name: Install dependencies
          command: npm install -g

      - run:
          name: Sync Database with ORM
          command: ./node_modules/.bin/typeorm schema:sync 
          
      - run:
          name: Run tests
          command: npm test --exit