version: 2

jobs:
  build:
    docker:
      - image: circleci/node:9.3
        environment:
          - PORT: 3000
          - PGUSER: 'test'
          - PGPASSWORD: 'test'
          - PGDATABASE: 'test'
          - PGHOST: 'localhost'
          - PGPORT: '5432'
    
      - image: circleci/postgres:10.1
        environment:
          - POSTGRES_USER: test
          - POSTGRES_DB: test
          - POSTGRES_PASSWORD: test

    steps:
      - checkout
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      - run:
          name: Change permissions from root to user
          command: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

      - run:
          name: Clean npm Cache
          command: npm cache clean --force

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Install Dev Dependencies
          command: npm install --only=dev

      - run:
          name: Sync Database with ORM
          command: ./node_modules/.bin/typeorm schema:sync 

      - run:
          name: Build server
          command: npm run build