version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          - PORT: 3000
          - PGUSER: 'test'
          - PGPASSWORD: 'test'
          - PGDATABASE: 'test'
          - PGHOST: 'localhost'
          - PGPORT: '5432'
    
      - image: circleci/postgres:10.1
        environment:
          - POSTGRES_USER: test
          - POSTGRES_DB: test
          - POSTGRES_PASSWORD: test

    steps:
      - checkout
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Sync Database with ORM
          command: ./node_modules/.bin/typeorm schema:sync 
          
      - run:
          name: Run tests
          command: npm test --exit